#ifndef FSM_HPP
#define FSM_HPP

#include "state.hpp"
#include <string>
#include <unordered_map>
#include <deque>
#include <chrono>

/**
 * @enum machineState
 * @brief Represents the possible states of the FSM's execution.
 * 
 * - IDLE: The FSM is not running.
 * - RUNNING: The FSM is actively processing inputs.
 * - STOPPED: The FSM has completed execution or was stopped manually.
 * - ERROR: The FSM encountered an error during execution.
 */
enum class machineState {
    IDLE,
    RUNNING,
    STOPPED,
    ERROR
};

/**
 * @class FSM
 * @brief Represents a Finite State Machine (FSM).
 * 
 * This class manages states, transitions, and the execution of the FSM. It provides
 * methods for adding/removing states, defining transitions, running the FSM, and debugging.
 */
class FSM {
private:
    std::unordered_map<std::string, std::shared_ptr<State>> states; ///< Map of state names to state objects for efficient lookups.
    std::unordered_map<std::string, std::shared_ptr<State>> finalStates; ///< Map of final states for quick access.
    std::string name; ///< Name of the FSM.
    std::string description; ///< Description of the FSM.
    std::chrono::milliseconds stepDelay; ///< Delay between FSM steps for precise timing.
    std::deque<char> input; ///< Input sequence for the FSM.
    std::deque<char> output; ///< Output sequence generated by the FSM.
    std::shared_ptr<State> startState; ///< Pointer to the start state of the FSM.
    std::shared_ptr<State> currentState; ///< Pointer to the current state during execution.
    machineState currentMachineState; ///< Current execution state of the FSM.
    std::chrono::milliseconds fsmRunTime; ///< Total runtime of the FSM.

public:
    /**
     * @brief Default constructor for FSM.
     * 
     * Initializes the FSM with default values.
     */
    FSM();

    /**
     * @brief Adds a new state to the FSM.
     * 
     * @param name The name of the state.
     * @param isFinal Indicates whether the state is a final state.
     */
    void addState(const std::string& name, bool isFinal);

    /**
     * @brief Removes a state from the FSM.
     * 
     * @param name The name of the state to remove.
     */
    void removeState(const std::string& name);

    /**
     * @brief Sets the start state of the FSM.
     * 
     * @param name The name of the start state.
     */
    void setStartState(const std::string& name);

    /**
     * @brief Adds a transition between two states.
     * 
     * @param fromState The name of the source state.
     * @param toState The name of the destination state.
     * @param input The input character that triggers the transition.
     */
    void addTransition(const std::string& fromState, const std::string& toState, char input);

    /**
     * @brief Removes a transition between two states.
     * 
     * @param fromState The name of the source state.
     * @param toState The name of the destination state.
     */
    void removeTransition(const std::string& fromState, const std::string& toState);

    /**
     * @brief Runs the FSM with a given input sequence.
     * 
     * @param inputSequence The sequence of inputs to process.
     */
    void run(const std::string& inputSequence);

    /**
     * @brief Debugs the FSM by generating a visualization.
     * 
     * Outputs a DOT file for Graphviz to visualize the FSM structure.
     */
    void debug();

    /**
     * @brief Gets the current state of the FSM.
     * 
     * @return A shared pointer to the current state.
     */
    std::shared_ptr<State> getCurrentState() const;

    /**
     * @brief Gets all states in the FSM.
     * 
     * @return A reference to the map of states.
     */
    const std::unordered_map<std::string, std::shared_ptr<State>>& getStates() const;

    /**
     * @brief Gets the start state of the FSM.
     * 
     * @return A shared pointer to the start state.
     */
    std::shared_ptr<State> getStartState() const;

    /**
     * @brief Gets all final states in the FSM.
     * 
     * @return A reference to the map of final states.
     */
    const std::unordered_map<std::string, std::shared_ptr<State>>& getFinalStates() const;

    /**
     * @brief Validates the FSM.
     * 
     * Checks for determinism and reachability of states.
     */
    void validateFSM();

    /**
     * @brief Removes all references to a state from other states.
     * 
     * @param stateName The name of the state to remove references to.
     */
    void removeReferencesToState(const std::string& stateName);

    /**
     * @brief Recursively deletes a state and its unreachable children.
     * 
     * @param name The name of the state to delete.
     */
    void deleteStateRecursive(const std::string& name);
};

#endif // FSM_HPP